<?php

/**
 * Implements hook_voipscript_get_script_names().
 */
function gtd_voipscript_get_script_names() {
  return array(
    'getthedoor',
  );
}

/**
 * Implements hook_load_script().
 */
function gtd_voipscript_load_script($script_name, $params = NULL) {
  if ($script_name == 'getthedoor') {
    $script = new VoipScript($script_name);

    $base = url(drupal_get_path('module', 'gtd'), array('absolute' => TRUE)) . '/audio';

    $num = variable_get('gtd_open_digit');
    $num_url = "$base/DTMF%20Tones/Dtmf-$num.wav";

    $script->addLabel('code');
    $script->addGetInput('Please enter your access code, followed by the pound sign. Or, wait to be connected.', 10, '#', 3);

    $script->addSet('check_zero', '^gtd_check_oper(%input_digits)');
    $script->addGotoIf('zero', '^gtd_check_oper(%input_digits)');

    $script->addSet('check_code', '^gtd_check_code(%input_digits)');

    $script->addGotoIf('success', '%check_code');

    // Fail
    $script->addSay('Sorry, that code was incorrect.');
    $script->addGoto('code');

    $script->addLabel('success');
    $script->addSay('Code accepted. Thanks!');
    $script->addSay($num_url);
    $script->addHangup();

    // Dial
    $script->addLabel('zero');
    $script->addSet('operator_name', variable_get('gtd_operator_name'));
    $script->addSay('Calling %operator_name');
    $script->addDial(variable_get('gtd_phone'));
    $script->addHangup();

    return $script;
  }
}

/**
 * Check if entered code matches correct code.
 */
function gtd_check_code($code) {
  return ($code == variable_get('gtd_code'));
}

/**
 * Check if entered code was 0.
 */
function gtd_check_oper($code) {
  return empty($code);
}

/**
 * Implements hook_menu().
 */
function gtd_menu() {
  $items = array();

  $items['admin/voip/gtd'] = array(
    'title' => 'GetTheDoor configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gtd_settings_form'),
    'access arguments' => array('adminsiter gtd'),
  );

  return $items;
}

/**
 * Implements hook_settings_form().
 */
function gtd_settings_form($form, $form_state) {
  $form = array();

  $form['gtd_code'] = array(
    '#title' => t('Access code'),
    '#description' => t('Enter the access code that will open the door.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('gtd_code'),
    '#required' => TRUE,
  );

  $form['gtd_operator_name'] = array(
    '#title' => t('Operator name'),
    '#description' => t('Enter the name of the operator..'),
    '#type' => 'textfield',
    '#default_value' => variable_get('gtd_operator_name'),
  );

  $form['gtd_operator_number'] = array(
    '#title' => t('Operator number'),
    '#description' => t('Enter the number that will be dialed with no access code.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('gtd_operator_number'),
  );

  $form['gtd_open_digit'] = array(
    '#title' => t('Open digit'),
    '#description' => t('Choose the button that opens the door.'),
    '#type' => 'select',
    '#default_value' => variable_get('gtd_open_digit'),
    '#options' => drupal_map_assoc(range(1,9)) + array(0 => 0, 'pound' => '#', 'star' => '*'),
  );

  return system_settings_form($form);
}
